version: 0.2

# ========================================
# Game Service Build Specification
# ========================================
# This buildspec builds the Docker image and pushes it to ECR
# Used by CodePipeline for automated ECS deployment

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Repository URI = $REPOSITORY_URI"
      - echo "Image Tag = $IMAGE_TAG"

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building Docker image from services/game-service..."
      - cd services/game-service
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file for ECS deployment..."
      - printf '[{"name":"game-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - cat imageDetail.json

artifacts:
  files:
    - imageDetail.json
  discard-paths: yes

cache:
  paths:
    - "/root/.docker/**/*"
