CREATE TABLE "modes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string,
  "description" string
);

CREATE TABLE "personal_record" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" string,
  "accuracy" float,
  "created_at" datetime DEFAULT (now()),
  "raw" float
);

CREATE TABLE "match_histories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mode_id" int,
  "created_at" datetime DEFAULT (now())
);

CREATE TABLE "match_participants" (
  "history_id" int,
  "account_id" string,
  "rank" int,
  "accuracy" float,
  "raw" float,
  PRIMARY KEY ("history_id", "account_id")
);

CREATE TABLE "achievements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string,
  "description" string,
  "wpm_criteria" int
);

CREATE TABLE "user_achievements" (
  "account_id" string,
  "achievement_id" int,
  PRIMARY KEY ("account_id", "achievement_id")
);

ALTER TABLE "match_histories" ADD FOREIGN KEY ("mode_id") REFERENCES "modes" ("id");

ALTER TABLE "match_participants" ADD FOREIGN KEY ("history_id") REFERENCES "match_histories" ("id");

ALTER TABLE "user_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("id");
