CREATE TABLE "roles" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string
);

CREATE TABLE "permissions" (
  "perm_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string
);

CREATE TABLE "role_permission" (
  "perm_id" int,
  "role_id" int,
  PRIMARY KEY ("perm_id", "role_id")
);

CREATE TABLE "user_ban" (
  "user_id" string PRIMARY KEY,
  "perm_id" int,
  "reason" string
);

ALTER TABLE "role_permission" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");
ALTER TABLE "role_permission" ADD FOREIGN KEY ("perm_id") REFERENCES "permissions" ("perm_id");
ALTER TABLE "user_ban" ADD FOREIGN KEY ("perm_id") REFERENCES "permissions" ("perm_id");